
import Database from "better-sqlite3";
import { writeFileSync, existsSync } from "fs";
import { join } from "path";

const DATA_DIR = join(process.cwd(), "data");
const DB_PATH = join(DATA_DIR, "gravity-claw.db");

if (!existsSync(DB_PATH)) {
    console.error("❌ Database file not found at:", DB_PATH);
    process.exit(1);
}

const db = new Database(DB_PATH);

function sqliteToPostgres(tableName) {
    try {
        const rows = db.prepare(`SELECT * FROM ${tableName}`).all();
        if (rows.length === 0) return "";

        let sql = `-- Data for ${tableName}\n`;
        
        for (const row of rows) {
            const columns = Object.keys(row);
            const values = Object.values(row).map(v => {
                if (v === null) return "NULL";
                if (typeof v === "string") return `'${v.replace(/'/g, "''")}'`;
                if (Buffer.isBuffer(v)) return `'\\x${v.toString("hex")}'`; // Postgres bytea hex format
                return v;
            });

            sql += `INSERT INTO ${tableName} (${columns.join(", ")}) VALUES (${values.join(", ")});\n`;
        }
        
        return sql + "\n";
    } catch (e) {
        return `-- Table ${tableName} skipped or error: ${e.message}\n`;
    }
}

let finalSql = `
-- Gravity Claw Supabase Migration Export
-- Generated on: ${new Date().toISOString()}

-- 1. Create Tables (Postgres Syntax)

CREATE TABLE IF NOT EXISTS memories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content TEXT NOT NULL,
    category TEXT DEFAULT 'facts',
    embedding BYTEA,
    importance INTEGER DEFAULT 1,
    metadata TEXT,
    media_type TEXT,
    media_url TEXT,
    access_count INTEGER DEFAULT 0,
    last_accessed TIMESTAMPTZ,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS knowledge_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    category TEXT DEFAULT 'general',
    embedding BYTEA,
    source_message_ids TEXT,
    access_count INTEGER DEFAULT 0,
    last_accessed TIMESTAMPTZ,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS conversations (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    message TEXT NOT NULL,
    response TEXT NOT NULL,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS entities (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    type TEXT DEFAULT 'concept',
    metadata TEXT,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS relationships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_id TEXT NOT NULL REFERENCES entities(id),
    target_id TEXT NOT NULL REFERENCES entities(id),
    relation TEXT NOT NULL,
    metadata TEXT,
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS user_settings (
    user_id BIGINT PRIMARY KEY,
    thinking_level TEXT DEFAULT 'off',
    briefing_time TEXT DEFAULT '08:00',
    recap_time TEXT DEFAULT '20:00'
);

CREATE TABLE IF NOT EXISTS scheduled_tasks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    cron_expression TEXT NOT NULL,
    prompt TEXT NOT NULL,
    status TEXT DEFAULT 'active',
    timestamp TIMESTAMPTZ DEFAULT CURRENT_TIMESTAMP
);

-- 2. Insert Data
`;

const tables = ["memories", "knowledge_items", "conversations", "entities", "relationships", "user_settings", "scheduled_tasks"];

for (const table of tables) {
    finalSql += sqliteToPostgres(table);
}

writeFileSync("data/supabase_dump.sql", finalSql);
console.log("✅ SQL dump generated at data/supabase_dump.sql");
